version: "3"

services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    restart: unless-stopped
    # Por algum motivo esses volumes estão sendo criados como root
    # volumes:
    #   - ./.docker/rabbitmq/data/:/var/lib/rabbitmq/
    #   - ./.docker/rabbitmq/logs/:/var/log/rabbitmq/
    environment: 
      # RABBITMQ_ERLANG_COOKIE: erlang_dev_only_cookie
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - 5672:5672
      - 15672:15672
    healthcheck:
      test: ['CMD', 'rabbitmq-diagnostics', '-q', 'ping']
      interval: 10s
      timeout: 5s
  phoenix:
    restart: unless-stopped
    build: ./cleber
    environment: 
      # postgresql://USER:PASSWORD@HOST/DB
      - DATABASE_URL=postgresql://elixir_pg:elixir_pg@localhost/elixir_pg
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672
      - SECRET_KEY_BASE=TESTING
      - ACCESS_TOKEN_SECRET=8f51exxxxxx7211dd
      - REFRESH_TOKEN_SECRET=dbb85xxxxxx9ebde
      # Variável para o sentry
      # - SENTRY_DSN=ASFACSAUN
      # se quiser alterar a porta do elixir
      # - PORT=8000
    depends_on: 
      - postgres
      - rabbitmq
    ports: 
      - 4000:4000
  postgres:
    image: postgres:13-alpine
    restart: unless-stopped
    # Esse volume foi comentado para evitar possível erro similar do rabbitmq
    # volumes:
    #   - ./.docker/postgres:/var/lib/postgresql/data
    # settar direto ou usar um .env
    environment:
      - POSTGRES_USER=elixir_pg
      - POSTGRES_PASSWORD=elixir_pg
      - POSTGRE_DB=elixir_pg
    ports:
      - 5432:5432
